server:
  port: 8091

mybatis:
  mapper-locations: classpath:mapper/*.xml


spring:
  datasource:
#    url: jdbc:mysql://43.226.74.12:3306/sfydb_6289594?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC&nuLlCatalogMeansCurrent=true
#    username: sfydb_6289594
#    password: Zc123456
    url: jdbc:mysql://localhost:3306/vuel?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC&nuLlCatalogMeansCurrent=true
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
#swagger
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

files:
  upload:
    path: d:/fileLocal/
    url: http://localhost:8091/file/

