server:
  port: 8091

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/lin?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC&nuLlCatalogMeansCurrent=true
    username: root
    password: root

  #  profiles:
  #    active: dev
  #mogoDb
#  data:
#    mongodb:
#      #      uri: mongodb://userlin:123456@172.16.87.175:27017/?authSource=lin
#      #      host: 121.89.203.197
#      host: 172.16.87.175
#      port: 27017
#      username: userlin
#      password: 123456
#      database: lin
  #      authentication-database: admin


  #mysql 多数据库连接实例
#  datasource:
#    #    type: com.alibaba.druid.pool.DruidDataSource
#    dynamic:
#      primary: master
#      strict: false #严格匹配数据源,默认false. true未匹配到指定数据源时抛异常,false使用默认数据源
#      datasource:
#        master:
#          driver-class-name: com.mysql.jdbc.Driver
#          url: jdbc:mysql://121.89.203.197:3306/xzs?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC&nuLlCatalogMeansCurrent=true
#          username: LJ
#          password: Qwe#1234
#
#        other:
#          driver-class-name: com.mysql.jdbc.Driver
#          url: jdbc:mysql://121.89.203.197:3306/ez_code?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC&nuLlCatalogMeansCurrent=true
#          username: LJ
#          password: Qwe#1234

  #redis 相关增删改查操作
  redis:
    host: 127.0.0.1
    jedis:
      pool:
        min-idle: 5
        max-idle: 10
        max-wait: -1


logging:
  level:
    org.springframework.data.mongodb.core: DEBUG



